---
dist: bionic
services:
  - docker

language: python
python:
  - "3.7"

env:
  global:
    - terragrunt_version: v0.23.10
  matrix:
  - distribution: centos-8
  - distribution: centos-7
  - distribution: fedora-32
  - distribution: fedora-31
  - distribution: fedora-30
  - distribution: fedora-29
  - distribution: fedora-28
  - distribution: fedora-27
  - distribution: fedora-26
  - distribution: ubuntu-20.04
  - distribution: ubuntu-18.04
  - distribution: ubuntu-16.04
  - distribution: ubuntu-14.04
  - distribution: debian-10
  - distribution: debian-9
  - distribution: debian-8
  - distribution: oraclelinux-7
  - distribution: amazonlinux-2
  - distribution: opensuse-15.1
  - distribution: opensuse-15
  - distribution: opensuse-42.3
  - distribution: opensuse-42.2
  - distribution: opensuse-13.2
  - distribution: archlinux-rolling
  - distribution: alpine-rolling
  - distribution: gentoo-stage3

before_install:
  - 'docker pull diodonfrost/${distribution}-ansible:latest'

install:
  - 'pip install molecule==3.0.6 docker==4.2.0 ansible==2.9.7'

script:
  - 'distribution=${distribution} terragrunt_version=${terragrunt_version} molecule test'

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
