---
- name: Verify
  hosts: all
  tasks:
    - name: Linux | Terragrunt should be functionnal
      command: terragrunt --version
      register: terragrunt_result

    - name: Linux | Verify commands outputs
      assert:
        that:
          - terragrunt_result.rc == 0
        success_msg: "All tests passed"
