---
- name: Verify
  hosts: all
  tasks:
  - name: Windows | Terragrunt should be functionnal
    win_command: terragrunt --version
    register: terragrunt_result

  - name: Windows | Verify commands outputs
    assert:
      that:
        - terragrunt_result.rc == 0
      success_msg: "All tests passed"
